---
# Handlers for common notifications.

- name: restart httpd
  service: name=httpd state=restarted
  when: ansible_distribution in ["CentOS","RedHat"]

- name: restart apache2
  service: name=apache2 state=restarted
  when: ansible_distribution in ["Ubuntu"]

# Munin is currently disabled on EL7
- name: restart munin
  service: name=munin-node state=restarted
  when: not (ansible_os_family == "RedHat" and ansible_distribution_major_version == "7")

- name: restart tower
  service: name=ansible-tower state=restarted
